### ISSUE TITLE
Cookies not working on iOS 13.3 beta

### ISSUE THREAD

**Issue by kas84** [ionic-team/cordova-plugin-ionic-webview#475]
Hi, since iOS 13.3 beta I am having issues with cookies not setting correctly on a cordova app.

I am using the latest version of ionic-webview:
`cordova-plugin-ionic-webview 4.1.3 "cordova-plugin-ionic-webview"`
I attach login response with set-cookie headers
![cookie failure](https://user-images.githubusercontent.com/5584/68842666-07f55a80-06c7-11ea-90a7-72495b3dc7bb.jpg)
And then check user get http without any cookie set.

![cookie-failure-2](https://user-images.githubusercontent.com/5584/68842890-6c181e80-06c7-11ea-8a89-944f1b7b10fd.jpg)

Anybody else experience this bug?

**Comment by NiklasMerz** [comment]
This is most likely a [Webkit bug](https://bugs.webkit.org/show_bug.cgi?id=204109)

**Comment by kas84** [comment]
Yes, seems like it, thanks! In case they don't fix it... is there a way to change http calls to go from a webkit http request to a native http request? I've checked https://ionicframework.com/docs/native/http, is there an easy way to integrate this into ionic v1 angularjs $http requests?

By the way, this also happens on iOS simulators since 12.0+

**Comment by NiklasMerz** [comment]
You might try #448 . I built this for cookie issues in the initial iOS 13 release. It works quite well if you can adjust all your URL to use the custom scheme.

**Comment by kas84** [comment]
What does that mean? I am using local http to serve the ionic app. Would I need to move to custom scheme like ionic://** ?

**Comment by NiklasMerz** [comment]
If you use the code from #448 via `https://github.com/NiklasMerz/cordova-plugin-ionic-webview#schemehandler` you can use the Javascript method `window.Ionic.WebView.convertFileSrc()` to convert your URLs.

Your HTTPS URL like `https://example.com` become `/_https_proxy_example.com`. This means your code will go through native methods of this plugin and you cookies will be set to the webview and all other requests.

**Comment by kas84** [comment]
Oh, I see. So basically when using a get like $http.get("https://google.com"), I should  do $http.get(window.Ionic.WebView.convertFileSrc("https://google.com")) and then it would go through the native layers?

**Comment by NiklasMerz** [comment]
> 
> 
> Oh, I see. So basically when using a get like $http.get("https://google.com"), I should do $http.get(window.Ionic.WebView.convertFileSrc("https://google.com")) and then it would go through the native layers?

Yes correct. Thats the idea of this PR. We call this 'proxy' because the HTTP requests are not done by Webkit but native URLSessions instead. This handles cookies correctly in the cookie store and syncs them to the webview.

**Comment by kas84** [comment]
Awesome! I'll check it out! Thanks!

**Comment by kas84** [comment]
On 13.3 beta 3 this bug is NOT fixed. I am not familiar with how Apple deploys versions, is there going to be a Golden Master before 13.3 goes mainstream?

That is, so we know for sure that they’re going to break this and need to go http native or not.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by NiklasMerz** [comment]
iOS 13.3 broke this again in different ways: https://bugs.webkit.org/show_bug.cgi?id=204109

We will see if it gets merged in for 13.3 GA. Always a suprise unfortunately.

**Comment by NiklasMerz** [comment]
But it did work at some point in 13.2 so I have hopes they will fix this regression.

**Comment by kas84** [comment]
I have the way around prepared with an if, but if I have to go http native and break sessions, I’d rather stay on http native even after they fix it.

Because I don’t want to break sessions twice

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by kas84** [comment]
Fixed by Apple on 13.3 beta 4

**Comment by Lucaszw** [comment]
This is working for me on a physical iPhone, but the cookie problem seems to be persisting with the iOS simulator. Is anyone else still encountering this?

**Comment by NiklasMerz** [comment]
This issue should be fixed by now. But maybe your simulator is on an older iOS version.

**Comment by kas84** [comment]
I’ll try it out and let you know. Is it supposed to be an iOS bug? Or ionic
webview bug that was fixed in the latest versions?

**Comment by NiklasMerz** [comment]
That was an iOS Webview Bug https://bugs.webkit.org/show_bug.cgi?id=204109

**Comment by kas84** [comment]
It still fails in my case. 

iOS version: 13.2.2
Version of the simulator:
Version 11.2.1 (SimulatorApp-912.4 SimulatorKit-570.3 CoreSimulator-681.15).

I don't know if any other plugin might be interfering but it's still not working on my side.

**Comment by NiklasMerz** [comment]
Make sure everything is updated. iOS 13 had some cookie issues. iOS 13.2 beta 2 fixed one. It broke after that in iOS 13.3 beta again and was fixes in iOS 13.3 beta 4. This is not a bug in the ionic webview plugin, but a bug in iOS. You need to find ways around that.

See those webkit bugs:
https://bugs.webkit.org/show_bug.cgi?id=200857

https://bugs.webkit.org/show_bug.cgi?id=204109

**Comment by alexsasharegan** [comment]
Both the simulator and the physical device are failing to include cookies. I tried the #448 code as well, but that just seems to crash my app.

iOS 13.3 (17C54)
Simulator Version 11.3.1 (SimulatorApp-912.5.1 SimulatorKit-570.3 CoreSimulator-681.17.2)

**Comment by danielsotopino** [comment]
Tested on simulator v13.3, not working.
Tested on device v13.3.1, it's working.

I'm going to check if v13.2 simulator works ok.
