### ISSUE TITLE
App fails to launch with Ionc WebView on iPad 2

### ISSUE THREAD

**Issue by mifkys** [ionic-team/cordova-plugin-ionic-webview#8]
I receive next error when run app on iPad 2 (iOS 9.3.5). All works on iPhone 5 Emulator (iOS 10.3):

```
2017-09-30 18:40:35.727 Dnevnik76[23115:4729599] DiskCookieStorage changing policy from 2 to 0, cookie file: file:///private/var/mobile/Containers/Data/Application/9B2440D6-F313-4DF0-9B6D-13A6D63239BF/Library/Cookies/Cookies.binarycookies
2017-09-30 18:40:35.824 Dnevnik76[23115:4729599] Apache Cordova native platform version 4.4.0 is starting.
2017-09-30 18:40:35.827 Dnevnik76[23115:4729599] Multi-tasking -> Device: YES, App: YES
2017-09-30 18:40:35.870 Dnevnik76[23115:4729599] CDVWKWebViewEngine: trying to inject XHR polyfill
2017-09-30 18:40:35.884 Dnevnik76[23115:4729599] -[WKWebViewConfiguration setMediaTypesRequiringUserActionForPlayback:]: unrecognized selector sent to instance 0x14673c90
2017-09-30 18:40:35.885 Dnevnik76[23115:4729599] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[WKWebViewConfiguration setMediaTypesRequiringUserActionForPlayback:]: unrecognized selector sent to instance 0x14673c90'
*** First throw call stack:
(0x2275f91b 0x21efae17 0x227652b5 0x22762ee1 0x2268e238 0x1403a7 0x14095f 0x29004d 0x28f75f 0x28fbfd 0x28d275 0xffd4b 0x26cdad8b 0x26cda971 0x26ce1639 0x26cdeb3d 0x26d53a5d 0x2918ef 0xffb21 0x26d4f785 0x26f772d1 0x26f7b285 0x26f8f83d 0x26f787b3 0x23e02c07 0x23e02ab9 0x23e02db9 0x22721dff 0x227219ed 0x2271fd5b 0x2266f229 0x2266f015 0x26d48c3d 0x26d43189 0xffa1b 0x22317873)
libc++abi.dylib: terminating with uncaught exception of type NSException
```
Environment:
```


    @ionic/cli-utils  : 1.12.0
    ionic (Ionic CLI) : 3.12.0

global packages:

    cordova (Cordova CLI) : 7.0.1 

local packages:

    @ionic/app-scripts : 3.0.0
    Cordova Platforms  : ios 4.4.0
    Ionic Framework    : ionic-angular 3.7.1

System:

    ios-deploy : 1.9.1 
    ios-sim    : 6.0.0 
    Node       : v6.11.0
    npm        : 3.10.10 
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b 

Misc:

    backend : legacy
```

Plugins:
```
cc.fovea.cordova.purchase 6.1.2 "Purchase"
cordova-plugin-camera 2.4.1 "Camera"
cordova-plugin-compat 1.1.0 "Compat"
cordova-plugin-device 1.1.4 "Device"
cordova-plugin-file 4.3.3 "File"
cordova-plugin-file-transfer 1.6.3 "File Transfer"
cordova-plugin-ionic-webview 1.1.8 "Ionic's WKWebView Engine"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.2.2 "StatusBar"
cordova-plugin-whitelist 1.3.1 "Whitelist"
ionic-plugin-keyboard 2.2.1 "Keyboard"
phonegap-plugin-push 2.0.0 "PushPlugin"
```

**Comment by manucorporat** [comment]
Fixed!

**Comment by mifkys** [comment]
All works like a charm! Thanks!

**Comment by giacomodeglinnocenti** [comment]
Still having this error in 2019.

cordova-plugin-android-permissions 1.0.0 "Permissions"
cordova-plugin-appcenter-analytics 0.3.6 "App Center Analytics for Cordova"
cordova-plugin-appcenter-crashes 0.3.6 "App Center Crashes for Cordova"
cordova-plugin-appcenter-shared 0.3.6 "App Center shared code for Cordova"
cordova-plugin-camera 4.1.0 "Camera"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 4.1.0 "cordova-plugin-ionic-webview"
cordova-plugin-nativeaudio 3.0.9 "Cordova Native Audio"
cordova-plugin-screen-orientation 3.0.2 "Screen Orientation"
cordova-plugin-speechrecognition 1.1.2 "Speech Recognition"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.3 "StatusBar"
cordova-plugin-tts 0.2.3 "TTS"
cordova-plugin-velda-devicefeedback 0.0.2 "DeviceFeedback"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-sqlite-storage 3.2.0 "Cordova sqlite storage plugin - cordova-sqlite-storage plugin version"
es6-promise-plugin 4.2.2 "Promise"




Ionic:

   Ionic CLI                     : 5.2.3 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.7.4
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.0.0, browser 6.0.0, ios 5.0.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.1.0, (and 15 other plugins)

Utility:

   cordova-res : 0.6.0 
   native-run  : 0.2.8 

System:

   Android SDK Tools : 26.1.1 (/Users/xxx/Library/Android/sdk)
   ios-deploy        : 1.9.4
   ios-sim           : 8.0.1
   NodeJS            : v8.16.0 (/usr/local/bin/node)
   npm               : 6.4.1
   OS                : macOS High Sierra
   Xcode             : Xcode 10.1 Build version 10B61




2019-08-12 07:22:27.782 Easit[348:97940] CDVWKWebViewEngine: trying to inject XHR polyfill
2019-08-12 07:22:27.798 Easit[348:97940] -[WKWebViewConfiguration setMediaTypesRequiringUserActionForPlayback:]: unrecognized selector sent to instance 0x14e64470
2019-08-12 07:22:27.799 Easit[348:97940] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[WKWebViewConfiguration setMediaTypesRequiringUserActionForPlayback:]: unrecognized selector sent to instance 0x14e64470'
*** First throw call stack:
(0x24acf91b 0x2426ae17 0x24ad52b5 0x24ad2ee1 0x249fe238 0xa04a5 0xa0f9b 0x1e975b 0x1e8efb 0x1e9399 0x1e6a35 0x8bb7f 0x2904ad8b 0x2904a971 0x29051639 0x2904eb3d 0x290c3a5d 0x1dc829 0x8b955 0x290bf785 0x292e72d1 0x292eb285 0x292ff83d 0x292e87b3 0x26172c07 0x26172ab9 0x26172db9 0x24a91dff 0x24a919ed 0x24a8fd5b 0x249df229 0x249df015 0x290b8c3d 0x290b3189 0x8b853 0x24687873)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by giacomodeglinnocenti** [comment]
**Still having this problem in 2019.**

2019-08-12 07:22:27.782 XXX[348:97940] CDVWKWebViewEngine: trying to inject XHR polyfill
2019-08-12 07:22:27.798 XXX[348:97940] -[WKWebViewConfiguration setMediaTypesRequiringUserActionForPlayback:]: unrecognized selector sent to instance 0x14e64470
2019-08-12 07:22:27.799 XXX[348:97940] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[WKWebViewConfiguration setMediaTypesRequiringUserActionForPlayback:]: unrecognized selector sent to instance 0x14e64470'
*** First throw call stack:
(0x24acf91b 0x2426ae17 0x24ad52b5 0x24ad2ee1 0x249fe238 0xa04a5 0xa0f9b 0x1e975b 0x1e8efb 0x1e9399 0x1e6a35 0x8bb7f 0x2904ad8b 0x2904a971 0x29051639 0x2904eb3d 0x290c3a5d 0x1dc829 0x8b955 0x290bf785 0x292e72d1 0x292eb285 0x292ff83d 0x292e87b3 0x26172c07 0x26172ab9 0x26172db9 0x24a91dff 0x24a919ed 0x24a8fd5b 0x249df229 0x249df015 0x290b8c3d 0x290b3189 0x8b853 0x24687873)
libc++abi.dylib: terminating with uncaught exception of type NSException
  
**---**

cordova-plugin-android-permissions 1.0.0 "Permissions"
cordova-plugin-appcenter-analytics 0.3.6 "App Center Analytics for Cordova"
cordova-plugin-appcenter-crashes 0.3.6 "App Center Crashes for Cordova"
cordova-plugin-appcenter-shared 0.3.6 "App Center shared code for Cordova"
cordova-plugin-camera 4.1.0 "Camera"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 4.1.0 "cordova-plugin-ionic-webview"
cordova-plugin-nativeaudio 3.0.9 "Cordova Native Audio"
cordova-plugin-screen-orientation 3.0.2 "Screen Orientation"
cordova-plugin-speechrecognition 1.1.2 "Speech Recognition"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.3 "StatusBar"
cordova-plugin-tts 0.2.3 "TTS"
cordova-plugin-velda-devicefeedback 0.0.2 "DeviceFeedback"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-sqlite-storage 3.2.0 "Cordova sqlite storage plugin - cordova-sqlite-storage plugin version"
es6-promise-plugin 4.2.2 "Promise"

**---**

ionic info

Ionic:

   Ionic CLI                     : 5.2.3 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.7.4
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.0.0, browser 6.0.0, ios 5.0.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.1.0, (and 15 other plugins)

Utility:

   cordova-res : 0.6.0 
   native-run  : 0.2.8 

System:

   Android SDK Tools : 26.1.1 (/Users/xxx/Library/Android/sdk)
   ios-deploy        : 1.9.4
   ios-sim           : 8.0.1
   NodeJS            : v8.16.0 (/usr/local/bin/node)
   npm               : 6.4.1
   OS                : macOS High Sierra
   Xcode             : Xcode 10.1 Build version 10B61

**Comment by giacomodeglinnocenti** [comment]
Reading other issues: 

https://github.com/ionic-team/cordova-plugin-ionic-webview/issues/303

No more support for iOs < 11?

Would be good to report it in the README or provide a workaround.

Thanks for your work.
